// Courses
const courses = [
  {
    id: '1',
    name: 'Software Engineering',
    description: 'Become a software developer today by taking this course',
    duration: '12 months',
    status: 'Active',
    projectId: '1',
  },
  {
    id: '2',
    name: 'Software Engineering',
    description: 'Become a software developer today by taking this course',
    duration: '12 months',
    status: 'Active',
    projectId: '2',
  },
  {
    id: '3',
    name: 'Software Engineering',
    description: 'Become a software developer today by taking this course',
    duration: '12 months',
    status: 'Active',
    projectId: '3',
  },
  {
    id: '4',
    name: 'Software Engineering',
    description: 'Become a software developer today by taking this course',
    duration: '12 months',
    status: 'Active',
    projectId: '4',
  },
  {
    id: '5',
    name: 'Software Engineering',
    description: 'Become a software developer today by taking this course',
    duration: '12 months',
    status: 'Active',
    projectId: '5',
  },
];

// Projects
const projects = [
  {
    id: '1',
    name: '0x00. Python - Hello, World',
    subject: 'Pyhton',
    weight: '1',
    team: 'Project to be done individually',
    startDate: 'Sep 6, 2021',
    endDate: 'Sep 7, 2021',
    status: 'Project over',
    progress: 'you are done with 200% of tasks',
    reviewType: 'An auto review will be launched at the deadline',
    autoQAReview: '89.0/89 mandatory & 27.0/27 optional',
    mandatoryScore: '100.0%',
    advancedScore: '100.0%',
    totalScore: '200.0%',
    concepts: 'Python programming',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.',
    tasks:
      'The peer learning day after this project, you (and your team if applicable) will present your project:',
    instructorId: '1',
  },
  {
    id: '2',
    name: 'Webstack - Portfolio Project',
    subject: 'Group project, Front-end, Back-end, Portfolio project',
    weight: '10',
    team: 'Project to be done in teams of 4 people',
    startDate: 'Sep 6, 2021',
    endDate: 'Sep 7, 2021',
    status: 'Ongoing project',
    progress: 'you are done with 200% of tasks',
    reviewType: 'An auto review will be launched at the deadline',
    autoQAReview: '89.0/89 mandatory & 27.0/27 optional',
    mandatoryScore: '100.0%',
    advancedScore: '100.0%',
    totalScore: '200.0%',
    concepts: 'Python programming',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.',
    tasks:
      'The peer learning day after this project, you (and your team if applicable) will present your project:',
    instructorId: '2',
  },
  {
    id: '3',
    name: '0x00. Python - Hello, World',
    subject: 'Pyhton',
    weight: '1',
    team: 'Project to be done in teams of 3 people',
    startDate: 'Sep 6, 2021',
    endDate: 'Sep 7, 2021',
    status: 'Project ongoing',
    progress: 'you are done with 200% of tasks',
    reviewType: 'An auto review will be launched at the deadline',
    autoQAReview: '89.0/89 mandatory & 27.0/27 optional',
    mandatoryScore: '100.0%',
    advancedScore: '100.0%',
    totalScore: '200.0%',
    concepts: 'Python programming',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.',
    tasks:
      'The peer learning day after this project, you (and your team if applicable) will present your project:',
    instructorId: '3',
  },
  {
    id: '4',
    name: '0x00. Python - Hello, World',
    subject: 'Pyhton',
    weight: '2',
    startDate: 'Sep 6, 2021',
    endDate: 'Sep 7, 2021',
    status: 'Project ongoing',
    progress: 'you are done with 200% of tasks',
    reviewType: 'An auto review will be launched at the deadline',
    autoQAReview: '89.0/89 mandatory & 27.0/27 optional',
    mandatoryScore: '100.0%',
    advancedScore: '100.0%',
    totalScore: '200.0%',
    concepts: 'Python programming',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.',
    tasks:
      'The peer learning day after this project, you (and your team if applicable) will present your project:',
    instructorId: '4',
  },
  {
    id: '5',
    name: '0x00. Python - Hello, World',
    subject: 'Pyhton',
    weight: '5',
    startDate: 'Sep 6, 2021',
    endDate: 'Sep 7, 2021',
    status: 'Project ongoing',
    progress: 'you are done with 200% of tasks',
    reviewType: 'An auto review will be launched at the deadline',
    autoQAReview: '89.0/89 mandatory & 27.0/27 optional',
    mandatoryScore: '100.0%',
    advancedScore: '100.0%',
    totalScore: '200.0%',
    concepts: 'Python programming',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.',
    tasks:
      'The peer learning day after this project, you (and your team if applicable) will present your project:',
    instructorId: '5',
  },
];

// Instructors
const instructors = [
  {
    id: '1',
    firstName: 'Ojok',
    middleName: 'Simon',
    lastName: 'Peter',
    gender: 'Male',
    dateOfBirth: 'June 03, 1993',
    address: 'Trinity College Gulu',
    email: 'afandeojok@gmail.com',
    password: 'pass123',
    phone: '0789-567-4333',
    nationality: 'Uganda',
    education: 'Master',
    status: 'Active',
  },
  {
    id: '2',
    firstName: 'Ojok',
    middleName: 'Simon',
    lastName: 'Simon Peter',
    gender: 'Male',
    dateOfBirth: 'June 03, 1993',
    address: 'Trinity College Gulu',
    email: 'ironman@gmail.com',
    password: 'pass123',
    phone: '343-567-4333',
    nationality: 'Uganda',
    education: 'Master',
    status: 'Active',
  },
  {
    id: '3',
    firstName: 'Ojok',
    middleName: 'Simon',
    lastName: 'Simon Peter',
    gender: 'Male',
    dateOfBirth: 'June 03, 1993',
    address: 'Trinity College Gulu',
    email: 'ironman@gmail.com',
    password: 'pass123',
    phone: '343-567-4333',
    nationality: 'Uganda',
    education: 'Master',
    status: 'Active',
  },
  {
    id: '4',
    firstName: 'Ojok',
    middleName: 'Simon',
    lastName: 'Simon Peter',
    gender: 'Male',
    dateOfBirth: 'June 03, 1993',
    address: 'Trinity College Gulu',
    email: 'ironman@gmail.com',
    password: 'pass123',
    phone: '343-567-4333',
    nationality: 'Uganda',
    education: 'Master',
    status: 'Active',
  },
  {
    id: '5',
    firstName: 'Ojok',
    middleName: 'Simon',
    lastName: 'Simon Peter',
    gender: 'Male',
    dateOfBirth: 'June 03, 1993',
    address: 'Trinity College Gulu',
    email: 'ironman@gmail.com',
    password: 'pass123',
    phone: '343-567-4333',
    nationality: 'Uganda',
    education: 'Master',
    status: 'Active',
  },
];

const students = [
  {
    id: '1',
    courseId: '1',
    firstName: 'Okello',
    middleName: '',
    lastName: 'Moses',
    gender: 'Male',
    dateOfBirth: 'June 3, 1991',
    emmergencyContactName: 'Aber Irene',
    emmergencyContactRelation: 'Spouse',
    emmergencyContactPhoneNumber: '+256 764 468 446',
    street: 'Olya Road',
    city: 'Gulu',
    zipcode: '000',
    state: 'Uganda',
    country: 'Uganda',
    email: 'afandeojok@gmail.com',
    password: 'pass123',
    phone: '+256 789 222 222',
    githubUsername: 'Jokmonsimon',
    twitterUsername: 'afandeojok',
    linkedInURL: 'https://www.linkedin.com/in/ojok-simon-peter/',
  },
  {
    id: '2',
    courseId: '1',
    firstName: 'Okello',
    middleName: '',
    lastName: 'Moses',
    gender: 'Male',
    dateOfBirth: 'June 3, 1991',
    emmergencyContactName: 'Aber Irene',
    emmergencyContactRelation: 'Spouse',
    emmergencyContactPhoneNumber: '+256 764 468 446',
    street: 'Olya Road',
    city: 'Gulu',
    zipcode: '000',
    state: 'Uganda',
    country: 'Uganda',
    email: 'afandeojok@gmail.com',
    password: 'pass123',
    phone: '+256 789 222 222',
    githubUsername: 'Jokmonsimon',
    twitterUsername: 'afandeojok',
    linkedInURL: 'https://www.linkedin.com/in/ojok-simon-peter/',
  },
  {
    id: '3',
    courseId: '1',
    firstName: 'Okello',
    middleName: '',
    lastName: 'Moses',
    gender: 'Male',
    dateOfBirth: 'June 3, 1991',
    emmergencyContactName: 'Aber Irene',
    emmergencyContactRelation: 'Spouse',
    emmergencyContactPhoneNumber: '+256 764 468 446',
    street: 'Olya Road',
    city: 'Gulu',
    zipcode: '000',
    state: 'Uganda',
    country: 'Uganda',
    email: 'afandeojok@gmail.com',
    password: 'pass123',
    phone: '+256 789 222 222',
    githubUsername: 'Jokmonsimon',
    twitterUsername: 'afandeojok',
    linkedInURL: 'https://www.linkedin.com/in/ojok-simon-peter/',
  },
  {
    id: '4',
    courseId: '1',
    firstName: 'Okello',
    middleName: '',
    lastName: 'Moses',
    gender: 'Male',
    dateOfBirth: 'June 3, 1991',
    emmergencyContactName: 'Aber Irene',
    emmergencyContactRelation: 'Spouse',
    emmergencyContactPhoneNumber: '+256 764 468 446',
    street: 'Olya Road',
    city: 'Gulu',
    zipcode: '000',
    state: 'Uganda',
    country: 'Uganda',
    email: 'afandeojok@gmail.com',
    password: 'pass123',
    phone: '+256 789 222 222',
    githubUsername: 'Jokmonsimon',
    twitterUsername: 'afandeojok',
    linkedInURL: 'https://www.linkedin.com/in/ojok-simon-peter/',
  },
  {
    id: '5',
    courseId: '1',
    firstName: 'Okello',
    middleName: '',
    lastName: 'Moses',
    gender: 'Male',
    dateOfBirth: 'June 3, 1991',
    emmergencyContactName: 'Aber Irene',
    emmergencyContactRelation: 'Spouse',
    emmergencyContactPhoneNumber: '+256 764 468 446',
    street: 'Olya Road',
    city: 'Gulu',
    zipcode: '000',
    state: 'Uganda',
    country: 'Uganda',
    email: 'afandeojok@gmail.com',
    password: 'pass123',
    phone: '+256 789 222 222',
    githubUsername: 'Jokmonsimon',
    twitterUsername: 'afandeojok',
    linkedInURL: 'https://www.linkedin.com/in/ojok-simon-peter/',
  },
];

module.exports = { projects, instructors, students, courses };
